fix: `TypeError: void 0 is not a function`
in browser or `TypeError: Client.makeDefault is not a function` by
running `bun test`.

`@effect/platform-browser` needs to have latest version.